/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as BuscarRouteImport } from './routes/buscar'
import { Route as ComoFuncionaRouteImport } from './routes/como-funciona'
import { Route as SolicitarRouteImport } from './routes/solicitar'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedClienteRouteImport } from './routes/_authenticated/cliente'
import { Route as AuthenticatedCuentaRouteImport } from './routes/_authenticated/cuenta'
import { Route as AuthenticatedMensajesRouteImport } from './routes/_authenticated/mensajes'
import { Route as AuthenticatedProRouteImport } from './routes/_authenticated/pro'
import { Route as ProProIdRouteImport } from './routes/pro.$proId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const BuscarRoute = BuscarRouteImport.update({
  id: '/buscar',
  path: '/buscar',
  getParentRoute: () => rootRouteImport,
} as any)
const ComoFuncionaRoute = ComoFuncionaRouteImport.update({
  id: '/como-funciona',
  path: '/como-funciona',
  getParentRoute: () => rootRouteImport,
} as any)
const SolicitarRoute = SolicitarRouteImport.update({
  id: '/solicitar',
  path: '/solicitar',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedClienteRoute = AuthenticatedClienteRouteImport.update({
  id: '/cliente',
  path: '/cliente',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCuentaRoute = AuthenticatedCuentaRouteImport.update({
  id: '/cuenta',
  path: '/cuenta',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMensajesRoute = AuthenticatedMensajesRouteImport.update({
  id: '/mensajes',
  path: '/mensajes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProRoute = AuthenticatedProRouteImport.update({
  id: '/pro',
  path: '/pro',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ProProIdRoute = ProProIdRouteImport.update({
  id: '/pro/$proId',
  path: '/pro/$proId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/buscar': typeof BuscarRoute
  '/como-funciona': typeof ComoFuncionaRoute
  '/solicitar': typeof SolicitarRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/cliente': typeof AuthenticatedClienteRoute
  '/cuenta': typeof AuthenticatedCuentaRoute
  '/mensajes': typeof AuthenticatedMensajesRoute
  '/pro': typeof AuthenticatedProRoute
  '/pro/$proId': typeof ProProIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/buscar': typeof BuscarRoute
  '/como-funciona': typeof ComoFuncionaRoute
  '/solicitar': typeof SolicitarRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/cliente': typeof AuthenticatedClienteRoute
  '/cuenta': typeof AuthenticatedCuentaRoute
  '/mensajes': typeof AuthenticatedMensajesRoute
  '/pro': typeof AuthenticatedProRoute
  '/pro/$proId': typeof ProProIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/buscar': typeof BuscarRoute
  '/como-funciona': typeof ComoFuncionaRoute
  '/solicitar': typeof SolicitarRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/cliente': typeof AuthenticatedClienteRoute
  '/_authenticated/cuenta': typeof AuthenticatedCuentaRoute
  '/_authenticated/mensajes': typeof AuthenticatedMensajesRoute
  '/_authenticated/pro': typeof AuthenticatedProRoute
  '/pro/$proId': typeof ProProIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/buscar'
    | '/como-funciona'
    | '/solicitar'
    | '/admin'
    | '/cliente'
    | '/cuenta'
    | '/mensajes'
    | '/pro'
    | '/pro/$proId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/buscar'
    | '/como-funciona'
    | '/solicitar'
    | '/admin'
    | '/cliente'
    | '/cuenta'
    | '/mensajes'
    | '/pro'
    | '/pro/$proId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/buscar'
    | '/como-funciona'
    | '/solicitar'
    | '/_authenticated/admin'
    | '/_authenticated/cliente'
    | '/_authenticated/cuenta'
    | '/_authenticated/mensajes'
    | '/_authenticated/pro'
    | '/pro/$proId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  BuscarRoute: typeof BuscarRoute
  ComoFuncionaRoute: typeof ComoFuncionaRoute
  SolicitarRoute: typeof SolicitarRoute
  ProProIdRoute: typeof ProProIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buscar': {
      id: '/buscar'
      path: '/buscar'
      fullPath: '/buscar'
      preLoaderRoute: typeof BuscarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/como-funciona': {
      id: '/como-funciona'
      path: '/como-funciona'
      fullPath: '/como-funciona'
      preLoaderRoute: typeof ComoFuncionaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solicitar': {
      id: '/solicitar'
      path: '/solicitar'
      fullPath: '/solicitar'
      preLoaderRoute: typeof SolicitarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/cliente': {
      id: '/_authenticated/cliente'
      path: '/cliente'
      fullPath: '/cliente'
      preLoaderRoute: typeof AuthenticatedClienteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/cuenta': {
      id: '/_authenticated/cuenta'
      path: '/cuenta'
      fullPath: '/cuenta'
      preLoaderRoute: typeof AuthenticatedCuentaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/mensajes': {
      id: '/_authenticated/mensajes'
      path: '/mensajes'
      fullPath: '/mensajes'
      preLoaderRoute: typeof AuthenticatedMensajesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pro': {
      id: '/_authenticated/pro'
      path: '/pro'
      fullPath: '/pro'
      preLoaderRoute: typeof AuthenticatedProRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/pro/$proId': {
      id: '/pro/$proId'
      path: '/pro/$proId'
      fullPath: '/pro/$proId'
      preLoaderRoute: typeof ProProIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedClienteRoute: typeof AuthenticatedClienteRoute
  AuthenticatedCuentaRoute: typeof AuthenticatedCuentaRoute
  AuthenticatedMensajesRoute: typeof AuthenticatedMensajesRoute
  AuthenticatedProRoute: typeof AuthenticatedProRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedClienteRoute: AuthenticatedClienteRoute,
  AuthenticatedCuentaRoute: AuthenticatedCuentaRoute,
  AuthenticatedMensajesRoute: AuthenticatedMensajesRoute,
  AuthenticatedProRoute: AuthenticatedProRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  BuscarRoute: BuscarRoute,
  ComoFuncionaRoute: ComoFuncionaRoute,
  SolicitarRoute: SolicitarRoute,
  ProProIdRoute: ProProIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
